// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ68DBXdt7sPVOXtVw8-tN3Lo6_iIBaFY',
    appId: '1:1069164250654:web:e0a280c2e3e6a32adad00f',
    messagingSenderId: '1069164250654',
    projectId: 'chat-41f07',
    authDomain: 'chat-41f07.firebaseapp.com',
    storageBucket: 'chat-41f07.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjjLwhthYXGBWhO844tbHrKVPo1bH1U8c',
    appId: '1:1069164250654:android:dd7bc2f1e5ec3b3adad00f',
    messagingSenderId: '1069164250654',
    projectId: 'chat-41f07',
    storageBucket: 'chat-41f07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4IANE1nn_cvsZaZqLgeXos3Lq4AVNwU0',
    appId: '1:1069164250654:ios:4890207297f0537fdad00f',
    messagingSenderId: '1069164250654',
    projectId: 'chat-41f07',
    storageBucket: 'chat-41f07.appspot.com',
    iosBundleId: 'com.example.chatHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4IANE1nn_cvsZaZqLgeXos3Lq4AVNwU0',
    appId: '1:1069164250654:ios:4890207297f0537fdad00f',
    messagingSenderId: '1069164250654',
    projectId: 'chat-41f07',
    storageBucket: 'chat-41f07.appspot.com',
    iosBundleId: 'com.example.chatHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ68DBXdt7sPVOXtVw8-tN3Lo6_iIBaFY',
    appId: '1:1069164250654:web:4d268b496c96e867dad00f',
    messagingSenderId: '1069164250654',
    projectId: 'chat-41f07',
    authDomain: 'chat-41f07.firebaseapp.com',
    storageBucket: 'chat-41f07.appspot.com',
  );
}
